### ISSUE TITLE
version of TFeat Model

### ISSUE THREAD

**Issue by mfaisal59** [ahojnnes/local-feature-evaluation#13]
Hi,
TFeat have 3 version of pretrained models provided on https://github.com/vbalnt/tfeat  which pretrained model did you use in your evaluations.

**Comment by ahojnnes** [comment]
As suggested by the author of TFeat, I used the Liberty model.

**Comment by mfaisal59** [comment]
Thank you for the clarification.

**Comment by mfaisal59** [comment]
Hi, We are using the TFeat model provided by the authors at https://github.com/vbalnt/tfeat , we are unable to reproduce the same results, especially the dense points on Fountain sequence are very less.

![fountrain_sequence_results](https://user-images.githubusercontent.com/40632568/47312418-be6a4580-d655-11e8-9fa1-6a24e7f11252.jpg)

**Comment by ahojnnes** [comment]
What happens when you run the pipeline again on the same dataset? Do you see consistent results?
