### ISSUE TITLE
Issue while trying to add a custom dataset

### ISSUE THREAD

**Issue by BobAlban** [ahojnnes/local-feature-evaluation#17]
Hello,

I'm trying to add custom datasets to your benchmark. My goal is to determine which method (SIFT, ...) is best for my specific application.

To do so, I tried to generate the file database.db associated with custom dataset. However, i can not figure out what *params* in the table *cameras* should contain (apparently it is binary data). Since i had no idea which kind of data i had to put here, i set NULL for every *camera_id*.

I generated descriptors, keypoints and matches successfully thanks to **scripts/matching_pipeline.m** (this script do not use database). However, when I try to run **scripts/reconstruction_pipeline.py** on my custom dataset, i get the following errors: 

```
==============================================================================
Loading database
==============================================================================

Loading cameras...F0917 10:12:14.569028  5185 database.cc:207] Check failed: num_params == camera.NumParams() (0 vs. 4) 
*** Check failure stack trace: ***
    @     0x7fd04f1b25cd  google::LogMessage::Fail()
    @     0x7fd04f1b4433  google::LogMessage::SendToLog()
    @     0x7fd04f1b215b  google::LogMessage::Flush()
    @     0x7fd04f1b4e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x6426a9  colmap::(anonymous namespace)::ReadCameraRow()
    @           0x647cd2  colmap::Database::ReadAllCameras()
    @           0x64b87d  colmap::DatabaseCache::Load()
    @           0x6ad367  colmap::IncrementalMapperController::LoadDatabase()
    @           0x6b0fba  colmap::IncrementalMapperController::Run()
    @           0x7f4eec  colmap::Thread::RunFunc()
    @     0x7fd04bb79c80  (unknown)
    @     0x7fd04e3a86ba  start_thread
    @     0x7fd04b2df41d  clone
    @              (nil)  (unknown)
Warning: Could not reconstruct any model

==============================================================================
Raw statistics
==============================================================================
{'num_inlier_matches': None, 'num_images': 43, 'num_inlier_pairs': 0}
None

==============================================================================
Formatted statistics
==============================================================================
Traceback (most recent call last):
  File "scripts/reconstruction_pipeline.py", line 297, in <module>
    main()
  File "scripts/reconstruction_pipeline.py", line 293, in main
    matching_stats["num_inlier_matches"]])) + " |")
TypeError: 'NoneType' object is not subscriptable
```

Do you have any idea what i did wrong here? Or anything i should consider to add a custom dataset to your benchmark?

**Comment by tsattler** [comment]
@BobAlban In order to run Structure-from-Motion, the database needs to contain information about the camera model that should be used for each image (ideally with some prior on the intrinsics). If you do not enter information into the database, the reconstruction part (which uses the Colmap library) will not work. That is the error you are encountering.
You can find more information about Colmap, its database format, and camera models here: https://colmap.github.io/index.html

**Comment by BobAlban** [comment]
thanks a lot for your quick answer. I will take a look at the database format then.
