### ISSUE TITLE
Make error: camera.cc.o  and src/CMakeFiles/colmap.dir/all.... seems to related to Ceres solver... 

### ISSUE THREAD

**Issue by GabbySuwichaya** [ahojnnes/local-feature-evaluation#21]
I have received the following error.

As I looked at the details, it seems that the error is related to the command lines of Ceres Solver which I have just recently updated (please see the figure below). 

Therefore, I guess that your developed package is relying on a certain Ceres's commit (about 2 years ago...). 

Can you share the commit id of the Ceres solver, so I can checkout the commit and works with your repo.?  

 ```   
src/CMakeFiles/colmap.dir/build.make:128: recipe for target 'src/CMakeFiles/colmap.dir/base/camera.cc.o' failed
make[2]: *** [src/CMakeFiles/colmap.dir/base/camera.cc.o] Error 1
CMakeFiles/Makefile2:853: recipe for target 'src/CMakeFiles/colmap.dir/all' failed
make[1]: *** [src/CMakeFiles/colmap.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

```
 
![Screenshot from 2020-06-18 10-43-20](https://user-images.githubusercontent.com/49115268/84968349-3d788f80-b151-11ea-901e-44d9996694c4.png)
 
![Screenshot from 2020-06-18 10-43-31](https://user-images.githubusercontent.com/49115268/84968358-41a4ad00-b151-11ea-813b-7fd214833af5.png)

**Comment by tsattler** [comment]
Did you compile ceres yourself? This looks like a compiler problem.

**Comment by GabbySuwichaya** [comment]
I have installed Ceres by following instruction from COLMAP (https://colmap.github.io/install.html) to which this  **Local-feature-evaluation repo** also seem to use it as the [reference](https://github.com/ahojnnes/local-feature-evaluation/issues/12) ..   

> sudo apt-get install libatlas-base-dev libsuitesparse-dev
git clone https://ceres-solver.googlesource.com/ceres-solver
cd ceres-solver
git checkout $(git describe --tags) # Checkout the latest release
mkdir build
cd build
cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
make
sudo make install

However, I have noticed that this **Local-feature-evaluation repo** seems to depends on a commit id (58d966c) which is referring to an old version of COLMAP. However, recently there seems to be a lot of changes in Ceres (master branch). 

So .... I think the solution is may be to use the old Ceres solver or to update this git repo. 

Actually, I have tried using the **recent** COLMAP version (dev branch) which can be succesfully built with the Ceres (master branch) and use them with this  **Local-feature-evaluation repo**. 

I found that the only change that I need to make was to change the name of the **export_path** argument to **output_path** in this [Line168](https://github.com/ahojnnes/local-feature-evaluation/blob/0a2f887a9745daba264479cd181ebefc211237b0/scripts/reconstruction_pipeline.py#L168). It works fine but some of the **numerical results** seem to **change**.... 

However, I have only try with the **Exhaustive Matching** mode which does not rely on the provide CMake file and vocab-tree in [colmap-tools](https://github.com/ahojnnes/local-feature-evaluation/tree/master/colmap-tools)  
I don't know if the provided  [CMake file](https://github.com/ahojnnes/local-feature-evaluation/blob/master/colmap-tools/CMakeLists.txt)  will work with the recent COMAP and Ceres version

**Comment by GabbySuwichaya** [comment]
The problem has gone a few months later. It is possible that it was the version of Ceres at that time.
