### ISSUE TITLE
missing vocab_tree_retriever_float/vocab_tree_builder_float

### ISSUE THREAD

**Issue by andrefaraujo** [ahojnnes/local-feature-evaluation#4]
It seems like colmap does not have `vocab_tree_retriever_float.cc` or `vocab_tree_builder_float.cc`, as described in the current version of the instructions when using large datasets.

I could only find versions without the "float" notation (eg, I can find `vocab_tree_retriever` but not `vocab_tree_retriever_float`).

I suppose one can use the non-float ones, but I would guess the performance would suffer a bit since the non-float ones perform quantization, while the "float" ones mentioned in the instructions probably perform no quantization (this is my guess).

**Comment by andrefaraujo** [comment]
Also, I don't see the variable `kDescDim`. It looks like you are using a version of colmap which is not yet available on github.

**Comment by andrefaraujo** [comment]
Okay, actually it seems like it is not straightforward to use `vocab_tree_builder` with the provided instructions, actually, since it does not take an argument `descriptor_path`. I was giving it a try to see if I could still get some result with the non-float version, but it seems like it is not straightforward.

**Comment by ahojnnes** [comment]
Checkout the ``colmap-tools`` folder as described in the instructions. Let me know if you have other questions.

**Comment by andrefaraujo** [comment]
oh, got it, I noticed the small change to the instructions to build that. Now all works. Thanks!
