### ISSUE TITLE
Error in match_descriptors (line 18): Unrecognized 'DISTANCE' argument: squaredeuclidean

### ISSUE THREAD

**Issue by biesseck** [ahojnnes/local-feature-evaluation#5]
In function **match_descriptors()** (line 18), the function **pdist2()** is called with 'squaredeuclidean' argument, but it is not in the list of valid methods (line 142). It should be replaced by 'euclidean' or 'seuclidean', right?

**Comment by ahojnnes** [comment]
``seuclidean`` is not the same as ``squaredeuclidean``, please refer to the documentation at https://ch.mathworks.com/help/stats/pdist2.html for details.

**Comment by biesseck** [comment]
My problem is I was using Matlab R2014a. In this version **pdist2()** function doesn't contain 'squaredeuclidean' option. I've got Matlab R2016b and now it's running ok. I thank you so much!!!
