### ISSUE TITLE
Cannot reproduce result of sift for madrid metropolis

### ISSUE THREAD

**Issue by rmitra** [ahojnnes/local-feature-evaluation#7]
Hi,
I could reproduce the result on Fountain, Herz-jesu, South-Building but cannot reproduce the result for Madrid Metropolis. The number of inliers-pairs and inlier -matches are way too many with lots of false positives. Is it a problem with inlier matching code?

**Comment by ahojnnes** [comment]
What do you mean by reproduce? Which feature are you talking about?

**Comment by rmitra** [comment]
I am using SIFT features obtained from vl_covdet as written in matching_pipeline.m

**Comment by ahojnnes** [comment]
The results in the table were obtained using a different SIFT implementation (the SiftGPU implementation). Can you post the numbers you are getting? It is normal that there are many outliers for the inlier pairs with few matches, as these are further filtered during reconstruction.

**Comment by rmitra** [comment]
==============================================================================
Raw statistics
==============================================================================
{'num_images': 1344, 'num_inlier_pairs': 623415, 'num_inlier_matches': 13696578}
{'num_reg_images': 471, 'num_sparse_points': 116959, 'num_observations': 678818, 'mean_track_length': 5.803897, 'num_observations_per_image': 1441.227176, 'mean_reproj_error': 0.598742, 'num_dense_points': 0}
==============================================================================Formatted statistics==============================================================================
Madrid_Metropolis | METHOD | 1344 | 471 | 116959 | 678818 | 5.803897 | 1441.227176 | 0.598742 | 0 |  |  |  |  | 623415 | 13696578

**Comment by ahojnnes** [comment]
Did you change any of the parameters or did you just use the pipeline as is?

**Comment by rmitra** [comment]
Use the pipeline as it is.

**Comment by ahojnnes** [comment]
Do you need this for an upcoming submission to be figured out or is later also fine? I am rather busy myself at the moment.

**Comment by rmitra** [comment]
I actually require this for an upcoming submission.

**Comment by ahojnnes** [comment]
Sorry, I didn't have time to look into this but plan to do so over the next days. Thanks for reporting the problem.

**Comment by ahojnnes** [comment]
Sorry for the very long delay, but there has been a lot of other work on my side. This should be fixed with the latest commit. Note that the numbers are also updated with the latest COLMAP version (or will be updated over the next days).
