### ISSUE TITLE
extremely slow running time of Gendarmenmarkt dataset

### ISSUE THREAD

**Issue by bfan** [ahojnnes/local-feature-evaluation#9]
I followed the instruction to reproduce the statistic result on the Gendarmenmarkt dataset. After conducting feature matching, it comes to
python scripts/reconstruction_pipeline.py \
     --dataset_path path/to/Fountain \
     --colmap_path path/to/colmap/build/src/exe
This script has already run over 3 days, so I think there might be something wrong?
I checked the task manager, and found that two threads are running:
~/colmap/build/src/exe/dense_fuser --workspace_path ~/data/Gendarmenmarkt/dense/0 --input_type photometric --output_path ~/data/Gendarmenmarkt/dense/0
~/colmap/build/src/exe/dense_fuser --workspace_path ~/data/Gendarmenmarkt/dense/0 --input_type photometric --output_path ~/data/Gendarmenmarkt/dense/0/fused.

Is this normal? Otherwise, how can I accelerate the process?

**Comment by ahojnnes** [comment]
Which Matlab version are you using and what GPU does your system have?

**Comment by bfan** [comment]
matlab R2015b, GPU is TITAN X (Pascal).  Below is the last output information I got:
....
WARNING: Ignoring image 981374980_1126f5a860_o.jpg, because input does not exist.
WARNING: Ignoring image 999273378_59e22a0646_o.jpg, because input does not exist.
Fusing image [1/1016] in 8.973s (29945 points)

I downloaded your supplied database file, and have not seen these warnings when loading features and matches by using your script: reconstruction_pipeline.py

**Comment by ahojnnes** [comment]
You need MATLAB 2016b or newer to run the matching on the GPU, which is why the pipeline is so slow for you. The matching part takes most of the time for most datasets. If you don’t have access to a newer matlab version, you could try and code the matching yourself using OpenCV.

**Comment by bfan** [comment]
Matching has done. I already run the matching_pipeline in Matlab. The slow running time is the final step in your instruction,  i.e., 

After finishing the matching pipeline, run the reconstruction using:
 python scripts/reconstruction_pipeline.py \
     --dataset_path path/to/Fountain \
     --colmap_path path/to/colmap/build/src/exe

And it comes to the final step "dense_fuser" as I saw the running thread of it.
According to your instruction, this step should not be so slow. Do I need to setup something?

**Comment by ahojnnes** [comment]
Are you running the dense fusion on a network drive by any chance? Or a slow drive in general?

**Comment by bfan** [comment]
Should not be this case. The disk I/O works well. I checked that there is no newer file was generated even the thread of "dense_fuser" was running over 5 days....
Previously, I used the smaller dataset "Fountain", everything went well.
Can you give me some instructions to solve this problem?

**Comment by ahojnnes** [comment]
How much RAM do you have on the machine?

**Comment by bfan** [comment]
256GB with 40 CPU(2.6GHz).

**Comment by ahojnnes** [comment]
Could you share the dense reconstruction folder with me?

**Comment by bfan** [comment]
Sure. The size of folder is large (over 1 GB), so I uploaded it on my homepage. Please refer to: www.nlpr.ia.ac.cn/fanbin/dense.rar
to get it.

**Comment by bfan** [comment]
Did you find any problem in my running?

**Comment by ahojnnes** [comment]
Please retry with the latest version of the benchmark. I upgraded the benchmark to the latest COLMAP version and am currently updating the numbers for the existing descriptors.
